openapi: 3.1.0
info:
  version: 1.0.0
  title: TesteoramaBackendSwagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Backend for Tasteorama studying project.
tags:
  - name: Recipes
    description: Operations with recipes.
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Operations  with user's information
  - name: Categories
    description: Operations with Categories
  - name: Ingredients
    description: Operations with Ingredients
servers:
  - url: https://tasteorama-idz6.onrender.com/api
paths:
  /recipes:
    get:
      $ref: '../swagger/paths/recipes/get.yaml'
    post:
      $ref: '../swagger/paths/recipes/post.yaml'
  /recipes/{recipeId}:
    get:
      $ref: '../swagger/paths/recipes/{recipeId}/get.yaml'
    delete:
      $ref: '../swagger/paths/recipes/{recipeId}/delete.yaml'
  /recipes/owned:
    get:
      $ref: '../swagger/paths/recipes/owned/get.yaml'
  /recipes/saved:
    get:
      $ref: '../swagger/paths/recipes/saved/get.yaml'
  /recipes/saved/{recipeId}:
    patch:
      $ref: '../swagger/paths/recipes/saved/{recipeId}/patch.yaml'
  /categories:
    get:
      $ref: '../swagger/paths/categories/get.yaml'
  /ingredients:
    get:
      $ref: '../swagger/paths/ingredients/get.yaml'
  /users:
    get:
      $ref: '../swagger/paths/users/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieRefresh:
      type: apiKey
      in: cookie
      name: refreshToken; Path=/; HttpOnly
    cookieSessionId:
      type: apiKey
      in: cookie
      name: sessionId; Path=/; HttpOnly
